const sampleListings = [
  {
    title: "Gold's Gym – Mumbai",
    description: "Gold's Gym in Mumbai offers world-class facilities, certified trainers, and a dynamic fitness environment. Perfect for all levels of fitness.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyfoE1VTu_tms1_aOePpqq9QHTQ79g-JEfAA&s",
    price: 3000,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Anytime Fitness – Delhi",
    description: "Anytime Fitness in Delhi offers cutting-edge equipment, flexible hours, and a supportive community.",
    image: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=800&q=80",
    price: 2800,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Powerhouse Gym – Bangalore",
    description: "This Bangalore-based powerhouse gym brings elite training, personal coaching, and transformation programs.",
    image: "https://content.jdmagicbox.com/v2/comp/bangalore/r4/080pxx80.xx80.220611010829.y7r4/catalogue/power-house-gym-lavakusha-nagar-bangalore-gyms-qh9y3935en.jpg",
    price: 3500,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Snap Fitness – Chennai",
    description: "Snap Fitness in Chennai focuses on 24/7 access, group workouts, and nutrition counseling.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    price: 2700,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Cult.Fit – Hyderabad",
    description: "Cult.Fit offers functional fitness classes, strength training, and mental wellness in Hyderabad.",
    image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_500,q_auto:eco,dpr_2,f_auto,fl_progressive/v1/cult-media/v2web/centers/center_941_IMAGE_62169d13-f4a6-40cc-86cb-d9b1eb61c346.png",
    price: 2500,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Muscle & Fitness – Pune",
    description: "Experience heavy lifting and cardio challenges at this hardcore gym in Pune.",
    image: "https://muscletime.in/wp-content/uploads/2025/03/IMG_0341-scaled.jpg",
    price: 3200,
    location: "Pune",
    country: "India",
  },
  {
    title: "Iron Paradise – Ahmedabad",
    description: "Iron Paradise offers the best bodybuilding equipment and personalized guidance in Ahmedabad.",
    image: "https://content.jdmagicbox.com/v2/comp/mumbai/x5/022pxx22.xx22.210324185913.n6x5/catalogue/iron-paradise-the-club-house-mira-road-thane-gyms-bsp3v2vy67.jpg",
    price: 2900,
    location: "Ahmedabad",
    country: "India",
  },
  {
    title: "Burn Gym – Jaipur",
    description: "Burn Gym provides HIIT, functional training, and pilates under expert supervision in Jaipur.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8vfp0Dkb0PfSxsf1bpIA9dDqhJo6sTGhVJw&s",
    price: 2100,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Fitness First – Kolkata",
    description: "Train like an athlete with international standards at Fitness First in Kolkata.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_lbTt3iXl_xta-sKZKk0Fk1qAZIjg6pnjdQ&s",
    price: 2800,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Revolution Fitness – Lucknow",
    description: "Revolutionize your routine with intense workouts and recovery sessions in Lucknow.",
    image: "https://plus.unsplash.com/premium_photo-1667516464620-f105167dc0c9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDUyfHx8ZW58MHx8fHx8",
    price: 2600,
    location: "Lucknow",
    country: "India",
  },
  {
    title: "The Fit District – Chandigarh",
    description: "A premium gym in Chandigarh offering Zumba, MMA, CrossFit, and more.",
    image: "https://images.unsplash.com/photo-1509475826633-fed577a2c71b?auto=format&fit=crop&w=800&q=80",
    price: 3000,
    location: "Chandigarh",
    country: "India",
  },
  {
    title: "Urban Muscle – Bhopal",
    description: "Bhopal’s Urban Muscle is perfect for serious lifters and transformation seekers.",
    image: "https://plus.unsplash.com/premium_photo-1664910169565-1fb3fc2b38b8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDY5fHx8ZW58MHx8fHx8",
    price: 1900,
    location: "Bhopal",
    country: "India",
  },
  {
    title: "Strive Strength – Nagpur",
    description: "Focus on strength and stamina at Nagpur’s top-rated fitness center.",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
    price: 2000,
    location: "Nagpur",
    country: "India",
  },
  {
    title: "Xtreme Zone – Patna",
    description: "Elevate your fitness game with bootcamps and pro coaching in Patna.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZReDmt3KZ-vz7DXtq6l0u9intNsClSK8kLg&s",
    price: 2300,
    location: "Patna",
    country: "India",
  },
  {
    title: "CoreFit – Ranchi",
    description: "Experience cutting-edge training techniques in Ranchi’s most advanced gym.",
    image: "https://content3.jdmagicbox.com/v2/comp/thane/m6/022pxx22.xx22.240218204432.l2m6/catalogue/corefit-gym-golden-nest-bhayandar-east-thane-gyms-dn3seik8li.jpg",
    price: 1850,
    location: "Ranchi",
    country: "India",
  },
  {
    title: "Body Temple – Surat",
    description: "Dedicated to muscle building and wellness, Body Temple leads fitness in Surat.",
    image: "https://content.jdmagicbox.com/v2/comp/surat/b7/0261px261.x261.230105231937.f5b7/catalogue/body-fitness-gym-katargam-surat-gyms-43ln36987p.jpg",
    price: 2400,
    location: "Surat",
    country: "India",
  },
  {
    title: "Elite Fitness – Vadodara",
    description: "Train smarter with elite coaches and structured programs in Vadodara.",
    image: "https://content.jdmagicbox.com/comp/def_content/gymnasiums/default-gymnasiums-10.jpg",
    price: 2700,
    location: "Vadodara",
    country: "India",
  },
  {
    title: "The Gym Lab – Noida",
    description: "Science-backed routines and equipment make this Noida’s top pick for results.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgZ1YARwA_Qy_z3ifuA2pjOomlrB1TZcC58Q&s",
    price: 3100,
    location: "Noida",
    country: "India",
  },
  {
    title: "Train Station – Gurgaon",
    description: "A modern fitness hub in Gurgaon offering strength, cardio, and wellness.",
    image: "https://plus.unsplash.com/premium_photo-1664475818952-ccfb804c1649?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDk1fHx8ZW58MHx8fHx8",
    price: 3300,
    location: "Gurgaon",
    country: "India",
  },
  {
    title: "Beast Mode Gym – Ludhiana",
    description: "Push your limits with powerful workouts in Ludhiana’s Beast Mode Gym.",
    image: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=800&q=80",
    price: 2200,
    location: "Ludhiana",
    country: "India",
  },
  {
    title: "Power Hub – Amritsar",
    description: "From beginners to pros, Power Hub offers facilities for everyone in Amritsar.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    price: 2500,
    location: "Amritsar",
    country: "India",
  },
  {
    title: "Gravity Gym – Dehradun",
    description: "Train with gravity defying machines and programs in Dehradun.",
    image: "https://content.jdmagicbox.com/comp/dehradun/p5/9999px135.x135.180411015604.y1p5/catalogue/gravity-fitness-badripur-dehradun-y4o5aerwkl.jpg",
    price: 2600,
    location: "Dehradun",
    country: "India",
  },
  {
    title: "MetroFlex – Mysore",
    description: "A true iron paradise for bodybuilders and fitness lovers in Mysore.",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGd5bXxlbnwwfHwwfHx8MA%3D%3D",
    price: 2400,
    location: "Mysore",
    country: "India",
  },
  {
    title: "Flex Appeal – Coimbatore",
    description: "Best gym in Coimbatore for strength training, yoga, and personal coaching.",
    image: "https://plus.unsplash.com/premium_photo-1664475844536-a89a2763efa3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 2000,
    location: "Coimbatore",
    country: "India",
  },
  {
    title: "Titanium Fitness – Vizag",
    description: "Vizag’s favorite gym with functional equipment and expert-led group sessions.",
    image: "https://plus.unsplash.com/premium_photo-1661963184425-96025bb77282?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8",
    price: 2700,
    location: "Vizag",
    country: "India",
  },
  {
    title: "Evolve Athletics – Guwahati",
    description: "Redefine your strength and mobility at Guwahati’s premium gym.",
    image: "https://plus.unsplash.com/premium_photo-1661920538067-c48451160c72?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 2100,
    location: "Guwahati",
    country: "India",
  },
  {
    title: "UrbanFit Studio – Thiruvananthapuram",
    description: "Modern fitness blended with tradition and nature in Kerala’s capital city.",
    image: "https://plus.unsplash.com/premium_photo-1661906008854-0343740e49d6?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 2300,
    location: "Thiruvananthapuram",
    country: "India",
  },
  {
    title: "The Fit Nest – Mangalore",
    description: "Functional fitness and modern workouts for every body type in Mangalore.",
    image: "https://plus.unsplash.com/premium_photo-1664908278139-003d064fcf28?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 2250,
    location: "Mangalore",
    country: "India",
  }
];

module.exports = { data: sampleListings };
